--- #YAML:1.0
name:                Form-Processor-Model-CDBI
version:             0.07
abstract:            model class for Form::Processor based on Class::DBI
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::DBI:                    3.0.0
    Form::Processor:               0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Bill Moseley
